#!/usr/bin/env python3
"""一个最小化、用于教学的 AI Agent Harness。"""

from mini_harness_core.session import (
    SESSIONS_DIR,
    SESSION_ID_PATTERN,
    SESSION_VERSION,
    SessionStore,
    utc_now,
)
from mini_harness_core.run_control import (
    RUN_CONTROL_FIELDS,
    RUN_CONTROL_STATES,
    can_schedule_action,
    create_run_control,
    mark_cancelled,
    mark_paused,
    request_cancel,
    request_pause,
    resume_run,
    settle_control_boundary,
    validate_run_control,
)
from mini_harness_core.retry import (
    DEFAULT_BASE_DELAY,
    DEFAULT_MAX_ATTEMPTS,
    FAILURE_CLASSES,
    RETRY_FIELDS,
    RETRY_POLICIES,
    RETRY_STATES,
    classify_failure,
    complete_retry,
    cooperative_backoff,
    create_retry_state,
    decide_retry,
    record_failure,
    reopen_retry_after_reconciliation,
    retry_context,
    start_attempt,
    validate_retry_state,
)
from mini_harness_core.durability import (
    ACTION_STATES,
    EFFECTS,
    REPLAY_POLICIES,
    create_action_checkpoint,
    default_replay_policy,
    expected_file_write,
    reconcile_file_observation,
    recover_action_checkpoint,
    recovery_control_state,
    summarize_observation,
    transition_action_checkpoint,
    validate_action_checkpoint,
)
from mini_harness_core.memory import (
    _SECRET_PATTERNS,
    MEMORY_CONTENT_LIMIT,
    MEMORY_CONTEXT_HEADER,
    MEMORY_FILE,
    MEMORY_KINDS,
    MEMORY_LIMIT,
    MEMORY_STORE_LIMIT,
    MemoryStore,
    format_memory_context,
    request_memory_approval,
    screen_memory_content,
    select_memories,
    validate_memory_candidate,
)
from mini_harness_core.project_context import (
    PROJECT_INSTRUCTIONS_FILE,
    SKILLS_DIRECTORY,
    SKILL_NAME_PATTERN,
    discover_skills,
    load_project_instructions,
    load_skill_body,
    select_skill,
)
from mini_harness_core.verification import (
    LS_OPTION_CHARS,
    SHELL_OPERATORS,
    _is_within_workspace,
    _normalized_workspace_path,
    _parse_shell_tokens,
    build_verification_feedback,
    extract_verification_target,
    is_related_verification,
)
from mini_harness_core.context import (
    COMPACTION_STRATEGY_VERSION,
    COMPACTION_EXCERPT_CHARACTERS,
    COMPACTION_RECENT_MESSAGES,
    COMPACTION_SUMMARY_ENTRIES,
    RUNTIME_CONTEXT_PREFIXES,
    TOKEN_ESTIMATOR_VERSION,
    RuntimeContextAssembler,
    compact_messages,
    measure_context,
    parse_context_budget,
    print_context_stats,
)
from mini_harness_core.mcp import (
    MCP_DEFAULT_TIMEOUT,
    MCP_EFFECT_READ_ONLY,
    MCP_EFFECT_SIDE_EFFECTING,
    MCP_EFFECT_UNKNOWN,
    MCP_PROTOCOL_VERSION,
    MCP_TOOL_REFERENCE,
    FakeMCPClient,
    MCPClient,
    MCPError,
    MCPRegistry,
    StdioMCPClient,
    execute_mcp_tool,
    validate_json_schema,
)
from mini_harness_core.authority import (
    DANGEROUS_COMMANDS,
    POLICY_ALLOW,
    POLICY_ASK,
    POLICY_DENY,
    SHELL_ENV_ALLOWLIST,
    _effective_subagent_authority,
    _policy_result,
    _tool_allowed,
    build_shell_environment,
    classify_shell,
    execute_shell,
    request_approval,
)
from mini_harness_core.policy_composition import (
    ALLOW as COMPOSE_ALLOW,
    ASK as COMPOSE_ASK,
    DENY as COMPOSE_DENY,
    CAPABILITY_PROFILES,
    EXTERNAL,
    GLOBAL_SECURITY_POLICY,
    HARNESS_LOCAL,
    NEUTRAL_DELEGATED_CEILING,
    READ_ONLY as POLICY_EFFECT_READ_ONLY,
    SIDE_EFFECTING as POLICY_EFFECT_SIDE_EFFECTING,
    TRUST_ZONES,
    WORKSPACE,
    CapabilityProfile,
    EffectivePolicy,
    RuntimeGateResult,
    SafetyReconciliationPermit,
    StaticPolicyLayer,
    compose_static_policy,
    compose_subagent_policy,
    delegated_ceiling,
    local_mcp_mapping,
    policy_for,
)
from mini_harness_core.policy_snapshot import (
    POLICY_DIRECTORY, POLICY_REVISION, POLICY_SCHEMA_VERSION,
    PolicyBinding, PolicySnapshotError, authority_diff, bind_current_policy,
    binding_from_events, build_policy_snapshot, canonical_json,
    compose_from_snapshot, effective_policy_reference, load_policy_snapshot, persist_snapshot,
    policy_drift, policy_fingerprint, replay_policy_events,
)
from mini_harness_core.providers import (
    FakeProvider,
    OpenAICompatibleHTTPClient,
    ProviderError,
    RealProvider,
    _ProtocolError,
)
from mini_harness_core.handoff import (
    HANDOFF_AUTHORITY_FIELDS,
    HANDOFF_FIELDS,
    HANDOFF_RETURN_FIELDS,
    HANDOFF_WORKSPACE_FIELDS,
    _contains_secret,
    _safe_result,
    _validate_string_list,
    create_handoff,
    validate_handoff,
)
from mini_harness_core.planning import (
    PLANNING_SCHEMA_VERSION,
    MAX_PLAN_STEPS,
    MAX_REPLANS,
    PLAN_STATUSES,
    STEP_STATUSES,
    block_step,
    complete_step,
    create_plan,
    fail_step,
    propose_step_completion,
    retry_exhausted_outcome,
    revise_plan,
    select_ready_step,
    start_step,
    subagent_result_evidence,
    validate_plan,
    validate_revision_history,
)
from mini_harness_core.run_manifest import (
    HARNESS_PROTOCOL_VERSION,
    HARNESS_RELEASE,
    MANIFEST_SCHEMA_VERSION,
    MODEL_PROTOCOL_MODE,
    RunManifestError,
    RunManifestStore,
    build_configuration,
    build_manifest,
    configuration_fingerprint,
    endpoint_identity,
    integrity_check,
    manifest_differences,
    rebuild_configuration_for_status,
)
from mini_harness_core.agent import run_agent, run_subagent
from mini_harness_core.audit import (
    ACTORS, AUDIT_DIR, AuditWriter, explain_events, format_timeline,
    list_runs, new_run_id, read_events, safe_observation_summary,
)
from mini_harness_core.governance import (
    Clock, FakeClock, GOVERNANCE_FIELDS, backoff_decision,
    consume_action, consume_safety_reconciliation, create_governance_state,
    deadline_status, effective_subagent_timeout, effective_tool_timeout,
    freeze_governance, governance_context, normal_action_decision,
    resume_governance, run_remaining, safety_reconciliation_decision,
    start_step_deadline, step_remaining, validate_governance_state,
)
from mini_harness_core.cli import (
    ENV_NAME_PATTERN,
    PROJECT_ROOT,
    forget_memory_interactively,
    list_memories,
    load_dotenv_local,
    main,
    update_memory_interactively,
)


if __name__ == "__main__":
    main()
