"""Application repository ports and durable run reservation types."""

from dataclasses import dataclass
from typing import Protocol

from .domain import (
    ContentCandidate, DeliveryRecord, Digest, Feedback, FeedbackResult,
    InterestProfile, Subscription,
)


@dataclass(frozen=True, slots=True)
class DigestRunRecord:
    digest_run_id: str
    subscription_id: str
    period_key: str
    harness_run_id: str
    status: str
    reason: str | None
    digest_id: str | None
    artifact_id: str | None
    harness_result: dict | None
    profile_version: int = 0
    profile_projection_id: str | None = None
    profile_projection: dict | None = None


class DigestRepository(Protocol):
    def save_subscription(self, subscription: Subscription) -> None: ...
    def get_subscription(self, subscription_id: str) -> Subscription | None: ...
    def list_subscriptions(self) -> tuple[Subscription, ...]: ...
    def reserve_digest_run(self, record: DigestRunRecord) -> tuple[DigestRunRecord, bool]: ...
    def save_candidates(self, digest_run_id: str,
                        candidates: tuple[ContentCandidate, ...]) -> None: ...
    def finish_digest_run(self, record: DigestRunRecord,
                          digest: Digest | None = None) -> None: ...
    def get_digest_run(self, digest_run_id: str) -> DigestRunRecord | None: ...
    def get_digest(self, digest_id: str) -> Digest | None: ...
    def get_profile(self, user_id: str) -> InterestProfile | None: ...
    def get_seen_content(self, user_id: str) -> frozenset[str]: ...
    def apply_feedback(self, feedback: Feedback, topic_keys: tuple[str, ...],
                       timestamp: str) -> FeedbackResult: ...
    def reserve_delivery(self, record: DeliveryRecord) -> tuple[DeliveryRecord, bool]: ...
    def reserve_delivery_retry(self, previous: DeliveryRecord,
                               record: DeliveryRecord) -> DeliveryRecord: ...
    def mark_delivery_dispatch_started(self, delivery_id: str,
                                       attempt_id: str) -> DeliveryRecord: ...
    def finish_delivery(self, record: DeliveryRecord) -> DeliveryRecord: ...
    def get_delivery(self, delivery_id: str) -> DeliveryRecord | None: ...
    def get_delivery_for_digest(self, digest_id: str,
                                channel: str) -> DeliveryRecord | None: ...
