"""Application repository ports and durable run reservation types."""

from dataclasses import dataclass
from typing import Protocol

from .domain import (
    AcceptedFlightPriceObservation, ApplicationOutbox, BriefingReservation,
    ConditionEvaluation, ConditionObservationRequest,
    ConditionSubscriptionCommit, ContentCandidate, Conversation,
    ConversationTurn, DefinitionOutcome, DeliveryRecord, Digest, Feedback,
    FeedbackResult, InterestProfile, ProductSubscription, Subscription,
    RelationEventAttempt, RelationEventOutbox, SubscriptionActivation,
    SubscriptionCommit, SubscriptionDefinition, TrackingDefinition,
    TrackingPolicySnapshot, TrackingUpdate, UpdateDistribution,
    UserSubscription,
)


@dataclass(frozen=True, slots=True)
class DigestRunRecord:
    digest_run_id: str
    subscription_id: str
    period_key: str
    harness_run_id: str
    status: str
    reason: str | None
    digest_id: str | None
    artifact_id: str | None
    harness_result: dict | None
    profile_version: int = 0
    profile_projection_id: str | None = None
    profile_projection: dict | None = None
    idempotency_key: str | None = None
    subscription_version: int = 1
    subscription_snapshot: dict | None = None
    harness_bound_at: str | None = None
    started_at: str | None = None
    updated_at: str | None = None
    failure_stage: str | None = None
    failure_code: str | None = None
    failure_subtype: str | None = None
    failure_diagnostics: dict | None = None
    definition_id: str | None = None
    definition_version: int | None = None


@dataclass(frozen=True, slots=True)
class RecoveryOperationRecord:
    operation_id: str
    application_run_id: str
    action: str
    status: str
    before_state: str
    after_state: str | None
    requested_at: str
    completed_at: str | None
    error_code: str | None


@dataclass(frozen=True, slots=True)
class GenerationAttemptRecord:
    attempt_id: str
    application_run_id: str
    attempt_number: int
    status: str
    request_metadata: dict
    response_metadata: dict | None
    failure_subtype: str | None
    started_at: str
    completed_at: str | None


@dataclass(frozen=True, slots=True)
class DefinitionAttemptRecord:
    attempt_id: str
    turn_id: str
    attempt_number: int
    status: str
    request_metadata: dict
    response_metadata: dict | None
    candidate_payload: dict | None
    failure_stage: str | None
    failure_subtype: str | None
    started_at: str
    completed_at: str | None


class DigestRepository(Protocol):
    def reserve_conversation(self, conversation: Conversation,
                             turn: ConversationTurn
                             ) -> tuple[Conversation, ConversationTurn, bool]: ...
    def reserve_conversation_turn(self, conversation_id: str, user_id: str,
                                  turn: ConversationTurn, maximum_turns: int,
                                  timestamp: str
                                  ) -> tuple[Conversation, ConversationTurn, bool]: ...
    def reserve_conversation_adjustment(
            self, conversation_id: str, user_id: str,
            turn: ConversationTurn, maximum_turns: int, timestamp: str,
            ) -> tuple[Conversation, ConversationTurn, bool]: ...
    def claim_conversation_turn(self, turn_id: str, owner_id: str,
                                timestamp: str) -> ConversationTurn | None: ...
    def finish_conversation_turn(self, turn: ConversationTurn,
                                 outcome: DefinitionOutcome,
                                 conversation_status: str,
                                 terminal_reason: str | None,
                                 timestamp: str
                                 ) -> tuple[Conversation, ConversationTurn,
                                            DefinitionOutcome]: ...
    def fail_conversation_turn(self, turn_id: str, error_code: str,
                               conversation_status: str, timestamp: str,
                               failure_stage: str | None = None,
                               failure_subtype: str | None = None
                               ) -> tuple[Conversation, ConversationTurn]: ...
    def get_conversation(self, conversation_id: str) -> Conversation | None: ...
    def get_conversation_turn(self, turn_id: str) -> ConversationTurn | None: ...
    def get_conversation_turn_by_key(self, conversation_id: str,
                                     idempotency_key: str
                                     ) -> ConversationTurn | None: ...
    def get_definition_outcome_for_turn(self, turn_id: str
                                        ) -> DefinitionOutcome | None: ...
    def get_definition_outcome(self, outcome_id: str
                               ) -> DefinitionOutcome | None: ...
    def list_conversation_turns(self, conversation_id: str
                                ) -> tuple[ConversationTurn, ...]: ...
    def list_definition_outcomes(self, conversation_id: str
                                 ) -> tuple[DefinitionOutcome, ...]: ...
    def reserve_definition_attempt(self, record: DefinitionAttemptRecord
                                   ) -> DefinitionAttemptRecord: ...
    def finish_definition_attempt(self, record: DefinitionAttemptRecord
                                  ) -> DefinitionAttemptRecord: ...
    def list_definition_attempts(self, turn_id: str
                                 ) -> tuple[DefinitionAttemptRecord, ...]: ...
    def commit_subscription_product(self, user_id: str,
                                    proposed: SubscriptionCommit,
                                    fault_injector=None
                                    ) -> SubscriptionCommit: ...
    def commit_condition_subscription_product(
            self, user_id: str, proposed: ConditionSubscriptionCommit,
            fault_injector=None) -> ConditionSubscriptionCommit: ...
    def get_subscription_commit_for_outcome(self, outcome_id: str
                                            ) -> SubscriptionCommit | None: ...
    def get_product_subscription(self, subscription_id: str
                                 ) -> ProductSubscription | None: ...
    def get_user_subscription_for_subscription(self, subscription_id: str
                                               ) -> UserSubscription | None: ...
    def get_subscription_definition(self, definition_id: str,
                                    definition_version: int
                                    ) -> SubscriptionDefinition | None: ...
    def get_tracking_definition(self, definition_id: str,
                                definition_version: int
                                ) -> TrackingDefinition | None: ...
    def get_tracking_policy(self, subscription_id: str, definition_id: str,
                            definition_version: int
                            ) -> TrackingPolicySnapshot | None: ...
    def get_pending_condition_request(self
                                      ) -> ConditionObservationRequest | None: ...
    def get_latest_condition_request_for_subscription(
            self, subscription_id: str) -> ConditionObservationRequest | None: ...
    def reserve_condition_request(self, record: ConditionObservationRequest
                                  ) -> tuple[ConditionObservationRequest, bool]: ...
    def fail_condition_request(self, request_id: str, failure_code: str,
                               timestamp: str
                               ) -> ConditionObservationRequest: ...
    def get_condition_evaluation(self, evaluation_id: str
                                 ) -> ConditionEvaluation | None: ...
    def get_latest_condition_evaluation_for_subscription(
            self, subscription_id: str) -> ConditionEvaluation | None: ...
    def link_condition_request(self, request_id: str, evaluation_id: str,
                               timestamp: str
                               ) -> ConditionObservationRequest: ...
    def complete_condition_request(
            self, request: ConditionObservationRequest,
            observation: AcceptedFlightPriceObservation,
            evaluation: ConditionEvaluation,
            update: TrackingUpdate | None,
            distribution: UpdateDistribution | None,
            fault_injector=None): ...
    def get_update_for_evaluation(self, evaluation_id: str
                                  ) -> TrackingUpdate | None: ...
    def list_tracking_updates(self, user_id: str,
                              subscription_id: str | None = None
                              ) -> tuple[TrackingUpdate, ...]: ...
    def get_distribution_for_update(self, update_id: str
                                    ) -> UpdateDistribution | None: ...
    def get_briefing_reservation(self, application_run_id: str
                                 ) -> BriefingReservation | None: ...
    def get_briefing_reservation_for_subscription(self, subscription_id: str
                                                  ) -> BriefingReservation | None: ...
    def get_application_outbox(self, outbox_id: str
                               ) -> ApplicationOutbox | None: ...
    def get_application_outbox_for_run(self, application_run_id: str
                                       ) -> ApplicationOutbox | None: ...
    def list_application_outbox(self) -> tuple[ApplicationOutbox, ...]: ...
    def claim_application_outbox(self, timestamp: str
                                 ) -> ApplicationOutbox | None: ...
    def finalize_application_outbox(self, outbox_id: str,
                                    expected_version: int, status: str,
                                    error_code: str | None,
                                    available_at: str, timestamp: str
                                    ) -> ApplicationOutbox: ...
    def get_relation_event(self, event_id: str
                           ) -> RelationEventOutbox | None: ...
    def get_relation_event_for_relation(self, user_subscription_id: str
                                        ) -> RelationEventOutbox | None: ...
    def list_relation_events(self) -> tuple[RelationEventOutbox, ...]: ...
    def get_relation_event_attempt(self, attempt_id: str
                                   ) -> RelationEventAttempt | None: ...
    def get_current_relation_event_attempt(self, event_id: str
                                           ) -> RelationEventAttempt | None: ...
    def list_relation_event_attempts(self, event_id: str
                                     ) -> tuple[RelationEventAttempt, ...]: ...
    def claim_relation_event(self, timestamp: str
                             ) -> RelationEventOutbox | None: ...
    def mark_relation_event_dispatch_started(self, event_id: str,
                                             expected_version: int,
                                             attempt_id: str,
                                             timestamp: str
                                             ) -> RelationEventAttempt: ...
    def finalize_relation_event(self, event_id: str, expected_version: int,
                                attempt_id: str, outcome: str,
                                error_code: str | None,
                                available_at: str, timestamp: str
                                ) -> RelationEventOutbox: ...
    def recover_relation_event(self, event_id: str, expected_version: int,
                               action: str, timestamp: str
                               ) -> RelationEventOutbox: ...
    def get_subscription_activation(self, activation_id: str
                                    ) -> SubscriptionActivation | None: ...
    def save_subscription(self, subscription: Subscription) -> None: ...
    def get_subscription(self, subscription_id: str) -> Subscription | None: ...
    def subscription_belongs_to_user(self, subscription_id: str,
                                     user_id: str) -> bool: ...
    def list_subscriptions(self) -> tuple[Subscription, ...]: ...
    def list_subscriptions_for_user(self, user_id: str) -> tuple[Subscription, ...]: ...
    def update_subscription(self, subscription: Subscription,
                            expected_version: int) -> bool: ...
    def reserve_digest_run(self, record: DigestRunRecord) -> tuple[DigestRunRecord, bool]: ...
    def reserve_first_briefing_run(self, outbox_id: str,
                                   record: DigestRunRecord
                                   ) -> tuple[DigestRunRecord, bool]: ...
    def save_candidates(self, digest_run_id: str,
                        candidates: tuple[ContentCandidate, ...]) -> None: ...
    def list_content_candidates(self, digest_run_id: str
                                ) -> tuple[ContentCandidate, ...]: ...
    def finish_digest_run(self, record: DigestRunRecord,
                          digest: Digest | None = None) -> None: ...
    def get_digest_run(self, digest_run_id: str) -> DigestRunRecord | None: ...
    def get_digest(self, digest_id: str) -> Digest | None: ...
    def list_digests(self, user_id: str,
                     subscription_id: str | None = None) -> tuple[Digest, ...]: ...
    def bind_digest_run(self, digest_run_id: str, harness_run_id: str,
                        timestamp: str) -> DigestRunRecord: ...
    def claim_bound_digest_run_recovery(self, digest_run_id: str,
                                        timestamp: str) -> DigestRunRecord: ...
    def mark_digest_run_recovery_required(self, digest_run_id: str,
                                          reason: str,
                                          timestamp: str) -> DigestRunRecord: ...
    def reserve_recovery_operation(self, record: RecoveryOperationRecord
                                   ) -> tuple[RecoveryOperationRecord, bool]: ...
    def finish_recovery_operation(self, record: RecoveryOperationRecord
                                  ) -> RecoveryOperationRecord: ...
    def get_recovery_operation(self, operation_id: str
                               ) -> RecoveryOperationRecord | None: ...
    def reserve_generation_attempt(self, record: GenerationAttemptRecord
                                   ) -> GenerationAttemptRecord: ...
    def finish_generation_attempt(self, record: GenerationAttemptRecord
                                  ) -> GenerationAttemptRecord: ...
    def list_generation_attempts(self, application_run_id: str
                                 ) -> tuple[GenerationAttemptRecord, ...]: ...
    def get_profile(self, user_id: str) -> InterestProfile | None: ...
    def get_seen_content(self, user_id: str) -> frozenset[str]: ...
    def apply_feedback(self, feedback: Feedback, topic_keys: tuple[str, ...],
                       timestamp: str) -> FeedbackResult: ...
    def reserve_delivery(self, record: DeliveryRecord) -> tuple[DeliveryRecord, bool]: ...
    def reserve_delivery_retry(self, previous: DeliveryRecord,
                               record: DeliveryRecord) -> DeliveryRecord: ...
    def mark_delivery_dispatch_started(self, delivery_id: str,
                                       attempt_id: str) -> DeliveryRecord: ...
    def finish_delivery(self, record: DeliveryRecord) -> DeliveryRecord: ...
    def get_delivery(self, delivery_id: str) -> DeliveryRecord | None: ...
    def get_delivery_for_digest(self, digest_id: str,
                                channel: str) -> DeliveryRecord | None: ...
